import type { BreakpointLayouts } from "./types";

export const DEFAULT_WIDGETS = [
  "threat-score",
  "email-volume",
  "severity-breakdown",
  "recent-threats",
  "pipeline-status",
  "geo-threat-map",
  "threat-origins",
  "top-senders",
  "dkim-spf-dmarc",
  "sandbox-queue",
  "infra-health",
];

export const DEFAULT_LAYOUTS: BreakpointLayouts = {
  lg: [
    { i: "threat-score",       x: 0, y: 0, w: 3, h: 2, minW: 2, minH: 2 },
    { i: "email-volume",       x: 3, y: 0, w: 5, h: 2, minW: 3, minH: 2 },
    { i: "severity-breakdown", x: 8, y: 0, w: 4, h: 2, minW: 2, minH: 2 },
    { i: "recent-threats",     x: 0, y: 2, w: 6, h: 3, minW: 3, minH: 2 },
    { i: "pipeline-status",    x: 6, y: 2, w: 3, h: 3, minW: 2, minH: 2 },
    { i: "geo-threat-map",     x: 9, y: 2, w: 3, h: 3, minW: 2, minH: 3 },
    { i: "threat-origins",     x: 0, y: 5, w: 3, h: 3, minW: 2, minH: 2 },
    { i: "top-senders",        x: 3, y: 5, w: 3, h: 3, minW: 2, minH: 2 },
    { i: "dkim-spf-dmarc",     x: 6, y: 5, w: 3, h: 3, minW: 2, minH: 2 },
    { i: "sandbox-queue",      x: 9, y: 5, w: 3, h: 3, minW: 2, minH: 2 },
    { i: "infra-health",       x: 0, y: 8, w: 4, h: 3, minW: 2, minH: 2 },
  ],
  md: [
    { i: "threat-score",       x: 0, y: 0, w: 3, h: 2, minW: 2, minH: 2 },
    { i: "email-volume",       x: 3, y: 0, w: 5, h: 2, minW: 3, minH: 2 },
    { i: "severity-breakdown", x: 0, y: 2, w: 4, h: 2, minW: 2, minH: 2 },
    { i: "recent-threats",     x: 4, y: 2, w: 4, h: 3, minW: 3, minH: 2 },
    { i: "pipeline-status",    x: 0, y: 4, w: 4, h: 3, minW: 2, minH: 2 },
    { i: "geo-threat-map",     x: 4, y: 5, w: 4, h: 3, minW: 2, minH: 3 },
    { i: "threat-origins",     x: 0, y: 7, w: 4, h: 3, minW: 2, minH: 2 },
    { i: "top-senders",        x: 4, y: 8, w: 4, h: 3, minW: 2, minH: 2 },
    { i: "dkim-spf-dmarc",     x: 0, y: 10, w: 4, h: 3, minW: 2, minH: 2 },
    { i: "sandbox-queue",      x: 4, y: 11, w: 4, h: 3, minW: 2, minH: 2 },
    { i: "infra-health",       x: 0, y: 13, w: 8, h: 3, minW: 2, minH: 2 },
  ],
  sm: [
    { i: "threat-score",       x: 0, y: 0,  w: 2, h: 2, minW: 2, minH: 2 },
    { i: "email-volume",       x: 2, y: 0,  w: 2, h: 2, minW: 2, minH: 2 },
    { i: "severity-breakdown", x: 0, y: 2,  w: 2, h: 2, minW: 2, minH: 2 },
    { i: "recent-threats",     x: 2, y: 2,  w: 2, h: 3, minW: 2, minH: 2 },
    { i: "pipeline-status",    x: 0, y: 4,  w: 2, h: 3, minW: 2, minH: 2 },
    { i: "geo-threat-map",     x: 0, y: 7,  w: 4, h: 3, minW: 2, minH: 3 },
    { i: "threat-origins",     x: 0, y: 10, w: 2, h: 3, minW: 2, minH: 2 },
    { i: "top-senders",        x: 2, y: 10, w: 2, h: 3, minW: 2, minH: 2 },
    { i: "dkim-spf-dmarc",     x: 0, y: 13, w: 2, h: 3, minW: 2, minH: 2 },
    { i: "sandbox-queue",      x: 2, y: 13, w: 2, h: 3, minW: 2, minH: 2 },
    { i: "infra-health",       x: 0, y: 16, w: 4, h: 3, minW: 2, minH: 2 },
  ],
  xs: [
    { i: "threat-score",       x: 0, y: 0,  w: 2, h: 2, minW: 2, minH: 2 },
    { i: "email-volume",       x: 0, y: 2,  w: 2, h: 2, minW: 2, minH: 2 },
    { i: "severity-breakdown", x: 0, y: 4,  w: 2, h: 2, minW: 2, minH: 2 },
    { i: "recent-threats",     x: 0, y: 6,  w: 2, h: 3, minW: 2, minH: 2 },
    { i: "pipeline-status",    x: 0, y: 9,  w: 2, h: 3, minW: 2, minH: 2 },
    { i: "geo-threat-map",     x: 0, y: 12, w: 2, h: 3, minW: 2, minH: 2 },
    { i: "threat-origins",     x: 0, y: 15, w: 2, h: 3, minW: 2, minH: 2 },
    { i: "top-senders",        x: 0, y: 18, w: 2, h: 3, minW: 2, minH: 2 },
    { i: "dkim-spf-dmarc",     x: 0, y: 21, w: 2, h: 3, minW: 2, minH: 2 },
    { i: "sandbox-queue",      x: 0, y: 24, w: 2, h: 3, minW: 2, minH: 2 },
    { i: "infra-health",       x: 0, y: 27, w: 2, h: 3, minW: 2, minH: 2 },
  ],
};
